#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/craftech360/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/craftech360/Desktop/Altio/Altio"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=2.0.1"
export "FLUTTER_BUILD_NUMBER=01"
export "DART_DEFINES=RkxVVFRFUl9BUFBfRkxBVk9SPXByb2Q="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=false"
export "TREE_SHAKE_ICONS=true"
export "PACKAGE_CONFIG=/Users/craftech360/Desktop/Altio/Altio/.dart_tool/package_config.json"
export "FLAVOR=prod"
