import 'package:capsoul/core/constants/constants.dart';
import 'package:capsoul/core/theme/app_colors.dart';
import 'package:capsoul/pages/home/custom_scaffold.dart';
import 'package:flutter/material.dart';

// Custom reusable Terms and Conditions widget
class TermsAndConditionsWidget extends StatelessWidget {
  final List<Map<String, dynamic>>? sections;

  const TermsAndConditionsWidget(
      {super.key, this.sections, this.onAccept, required this.showAcceptBtn});
  final bool showAcceptBtn;
  final VoidCallback? onAccept;

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: EdgeInsets.all(12),
      child: CustomScaffold(
        title: Text(
          "Terms and Conditions",
          style: TextStyle(fontWeight: FontWeight.w500, fontSize: 19),
        ),
        showBackBtn: true,
        body: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 6),
          child: Column(
            children: [
              Expanded(
                child: ListView.builder(
                  itemCount: sections?.length,
                  itemBuilder: (context, index) {
                    final section = sections?[index];
                    return Padding(
                      padding: const EdgeInsets.only(bottom: 16.0),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            section?['heading'],
                            style: const TextStyle(
                              fontWeight: FontWeight.bold,
                              fontSize: 18,
                            ),
                          ),
                          const SizedBox(height: 8),
                          ...section?['points']
                              .map<Widget>((point) => Text('• $point'))
                              .toList(),
                        ],
                      ),
                    );
                  },
                ),
              ),
              Visibility(
                visible: showAcceptBtn,
                child: ElevatedButton(
                  onPressed: onAccept,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: AppColors.purpleDark,
                    foregroundColor: AppColors.white,
                    shape: RoundedRectangleBorder(borderRadius: br8),
                  ),
                  child: const Text(
                    'I Accept',
                    style: TextStyle(fontSize: 15, fontWeight: FontWeight.w600),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

void showTermsDialog(BuildContext context) {
  final List<Map<String, dynamic>> sections = [
    {
      'heading': "Introduction",
      'points': [
        'These Terms and Conditions govern your use of the app.',
        'By using this app, you confirm that you understand and agree to comply with these terms.',
        'The app is designed to transcribe real-time voice recordings and store them in your phone’s storage for future reference.',
      ],
    },
    {
      'heading': "General Terms",
      'points': [
        'The app is provided as-is without any warranties.',
        'We reserve the right to update the terms at any time.',
      ],
    },
    {
      'heading': "Voice Recording and Transcription",
      'points': [
        'The app allows the recording of real-time audio through a Bluetooth device connected to your mobile phone.',
        'AI-powered transcription services are used to convert the recorded voice into text.',
        'All recorded data and transcriptions are stored locally on your device unless explicitly stated otherwise.',
      ],
    },
    {
      'heading': "Data Storage and Management",
      'points': [
        'Transcriptions generated by the app are stored in your phone’s storage as a memory.',
        'You are responsible for managing and backing up your data.',
        'The app does not store any audio or transcription data on external servers unless specified in additional features or settings.',
      ],
    },
    {
      'heading': "Bluetooth Device Integration",
      'points': [
        'The app requires a Bluetooth device for voice recording.',
        'The app is designed to work with compatible Bluetooth devices, and you must ensure that your device is correctly paired with the app.',
        'We are not responsible for any malfunctions, data loss, or incompatibility issues with the Bluetooth device.',
      ],
    },
    {
      'heading': "Privacy and Data Protection",
      'points': [
        'The app will not share your recordings or transcriptions with third parties unless explicitly authorized by you.',
        'We may collect anonymized usage data for the purpose of improving the app’s functionality.',
        'By using the app, you consent to the collection of data related to the app’s performance and usage patterns.',
      ],
    },
    {
      'heading': "User Responsibility",
      'points': [
        'You are responsible for ensuring that you have permission to record and transcribe any conversations.',
        'The app must not be used for any illegal activities, including but not limited to recording conversations without consent.',
        'You are solely responsible for the legality of using this app in your jurisdiction.',
      ],
    },
    {
      'heading': "Intellectual Property",
      'points': [
        'All content, design, and functionality of the app are protected by intellectual property laws.',
        'You are granted a limited, non-transferable license to use the app for personal, non-commercial purposes.',
      ],
    },
    {
      'heading': "Limitation of Liability",
      'points': [
        'The app is provided "as-is" without any warranty of any kind, either express or implied.',
        'We are not liable for any direct, indirect, incidental, or consequential damages arising from the use of the app, including loss of data, malfunction, or failure to transcribe voice recordings correctly.',
      ],
    },
    {
      'heading': "Updates and Modifications",
      'points': [
        'The app may be updated periodically, and the Terms and Conditions may change with each update.',
        'We reserve the right to modify or discontinue the app at any time without prior notice.',
      ],
    },
    {
      'heading': "Termination",
      'points': [
        'We reserve the right to suspend or terminate your access to the app at any time if you violate these Terms and Conditions.',
        'Termination of access does not affect any obligations or rights accrued before the termination.',
      ],
    },
    {
      'heading': "Governing Law",
      'points': [
        'These Terms and Conditions are governed by the laws of the jurisdiction where you reside.',
        'Any legal disputes related to the use of the app will be subject to the exclusive jurisdiction of the courts in your jurisdiction.',
      ],
    },
    {
      'heading': "Contact Us",
      'points': [
        'If you have any questions regarding these Terms and Conditions, please contact us at craftechapps@gmail.com',
      ],
    },
  ];

  showDialog(
    barrierDismissible: false,
    context: context,
    builder: (BuildContext context) {
      return TermsAndConditionsWidget(
        sections: sections,
        showAcceptBtn: false,
      );
    },
  );
}
