version: 2.1

jobs:
  build:
    macos:
      xcode: 15.3.0
    working_directory: ~/repo/apps/AppWithWearable # Update working directory

    steps:
      - checkout

      # Install Flutter dependencies
      - run:
          name: Install Flutter
          command: |
            git clone https://github.com/flutter/flutter.git -b stable
            export PATH="$PATH:`pwd`/flutter/bin"
            flutter doctor

      - run:
          name: Flutter pub get
          command: flutter pub get

      # Build iOS
      - run:
          name: Build iOS
          command: flutter build ios --release --no-codesign

      # Install Fastlane
      - run:
          name: Install Fastlane
          command: |
            gem install bundler
            bundle install

      # Deploy to TestFlight using Fastlane
      - run:
          name: Deploy to TestFlight
          command: bundle exec fastlane beta
          working_directory: ios # Assuming your Fastfile is in the 'ios' directory

    environment:
      APPLE_ID: $APPLE_ID
      APPLE_PASSWORD: $APPLE_PASSWORD
      FASTLANE_USER: $FASTLANE_USER
      FASTLANE_PASSWORD: $FASTLANE_PASSWORD
      PINECONE_INDEX_NAMESPACE: $PINECONE_INDEX_NAMESPACE
      CUSTOM_TRANSCRIPT_API_BASE_URL: $CUSTOM_TRANSCRIPT_API_BASE_URL
      PINECONE_API_KEY: $PINECONE_API_KEY
      PINECONE_INDEX_URL: $PINECONE_INDEX_URL
      SENTRY_DSN_KEY: $SENTRY_DSN_KEY
      OPENAI_API_KEY: $OPENAI_API_KEY
      DEEPGRAM_API_KEY: $DEEPGRAM_API_KEY

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_ios:
          filters:
            branches:
              only: development
