# .circleci/config.yml
version: 2.1

jobs:
  build_ios:
    macos:
      xcode: 14.0.1
    working_directory: ~/repo

    steps:
    - checkout
  
   # Set Fastlane User and Password from environment variables
    - run:
        name: Set Fastlane User and Password
        command: |
            echo "export FASTLANE_USER='${{ secrets.FASTLANE_USER }}'" >> $BASH_ENV
            echo "export FASTLANE_PASSWORD='${{ secrets.FASTLANE_PASSWORD }}'" >> $BASH_ENV

    # Install Flutter
    - run:
        name: Install Flutter
        command: |
          git clone https://github.com/flutter/flutter.git -b stable
          echo 'export PATH="$PATH:`pwd`/flutter/bin"' >> $BASH_ENV
          source $BASH_ENV
          flutter doctor

    - run:
        name: Flutter pub get
        command: |
          cd apps/AppWithWearable
          flutter pub get

      # Get Flutter packages
    - run:
        name: Run code generation
        command: |
          cd apps/AppWithWearable
          flutter pub run build_runner build --delete-conflicting-outputs

      # Run code generation
    - run:
        name: Build iOS
        command: |
          cd apps/AppWithWearable
          flutter build ios --release --no-codesign

      # Build iOS
    - run:
        name: Install Bundler
        command: |
          cd apps/AppWithWearable/ios
          gem install bundler -v 2.4.22

      # Install Bundler (specific version)
    - run:
        name: Bundle install
        command: |
          cd apps/AppWithWearable/ios
          bundle _2.4.22_ install

      # Bundle install
    - run:
        name: Deploy to TestFlight
        command: |
          cd apps/AppWithWearable/ios
          bundle exec fastlane custom_lane

      # Deploy to TestFlight
   
workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build_ios:
        filters:
          branches:
            only: development
