name: friend_private
description: A new Flutter project.

publish_to: "none"

version: 1.0.20+86

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # animated_text_kit: ^4.2.2
  archive: ^3.6.1
  auto_size_text:
  awesome_notifications:
  awesome_notifications_core:
  # cached_network_image: ^3.4.0
  # collection: 1.18.0
  # crypto: ^3.0.3
  deepgram_speech_to_text: ^2.1.1
  device_calendar: ^4.3.2

  # docx_template: ^0.4.0
  encrypt:
  envied:
  equatable: 2.0.5
  #  fonnx:
  #    git:
  #      url: https://github.com/Telosnex/fonnx.git
  #      ref: main
  # expandable_text: ^2.3.0
  # file_picker: ^8.0.5
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.6
  flutter_bloc: ^8.1.6
  flutter_blue_plus: ^1.32.7
  flutter_foreground_task: ^6.5.0

  flutter_localizations:
    sdk: flutter
  flutter_markdown:
  # flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  # flutter_silero_vad:
  #   git:
  #     url: https://github.com/char5742/flutter_silero_vad.git
  # flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  # flutter_tilt: any
  flutter_timezone: ^2.0.0
  # font_awesome_flutter: 10.6.0
  # from_css_color: 2.0.0
  go_router: ^14.3.0
  google_sign_in: ^6.2.1
  googleapis_auth: ^1.6.0
  googleapis: ^13.2.0
  gradient_borders:
  groq: ^0.0.5
  growthbook_sdk_flutter: ^3.9.2
  http: ^1.2.1
  instabug_flutter: 14.0.0
  instabug_http_client: 2.5.0
  internet_connection_checker_plus: ^2.5.0
  intl: ^0.19.0
  location:
  logger: ^2.4.0
  lottie: ^3.1.2
  map_launcher: ^3.3.1
  # mime: ^1.0.5
  # mime_type:

  #  flutter_foreground_task: ^6.2.0
  mixpanel_flutter: ^2.2.0
  # ml_linalg: any
  objectbox: ^4.0.1
  objectbox_flutter_libs: any
  onesignal_flutter: ^5.2.5
  opus_dart: ^3.0.1
  opus_flutter: ^3.0.2
  # nordic_dfu: ^6.1.4+hotfix
  # package_info_plus: ^8.0.0
  # page_transition: 2.1.0
  path: ^1.9.0

  path_provider:
  pdf:
  permission_handler: ^11.3.1
  provider: ^6.1.2
  record: ^5.1.2
  # restart_app: ^1.2.1
  share_plus:

  shared_preferences: ^2.2.3
  shimmer:
  # sign_in_button: ^3.2.0
  sign_in_with_apple: ^6.1.1
  # smooth_page_indicator:
  swipe: ^0.0.1
  timelines: ^0.1.0
  # top_snackbar_flutter: ^3.1.0
  tuple: ^2.0.2
  upgrader: ^10.3.0
  url_launcher: ^6.3.0
  url_launcher_platform_interface:
  uuid:
  wav: ^1.3.0
  web_socket_channel:
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      ref: b783000

dependency_overrides:
  http: ^1.2.1
  opus_flutter_ios:
    git:
      url: https://github.com/mdmohsin7/opus_flutter.git
      path: opus_flutter_ios
      ref: dev
  opus_flutter_android:
    git:
      url: https://github.com/mdmohsin7/opus_flutter.git
      path: opus_flutter_android
  # web: ^1.0.0
dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  build_runner: ^2.4.11
  envied_generator:
  flutter_flavorizr: ^2.2.3
  # flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  # image: ^4.2.0
  integration_test:
    sdk: flutter
  # lints: ^4.0.0
  objectbox_generator:

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_launcher_icon.png"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 24
  remove_alpha_ios: true
  android_notification_icon: "assets/images/ic_stat_launcher.png"