name: avm
description: "A new Flutter project."
publish_to: "none"
version: 1.0.20+88

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  
  logging: ^1.0.2  
  archive: ^3.6.1
  auto_size_text: ^3.0.0
  awesome_notifications: ^0.10.0
  awesome_notifications_core: ^0.10.0
  bloc: ^8.1.4
  flutter_secure_storage: ^5.0.2
  collection: 1.19.0
  connectivity_plus: ^6.1.1
  crypto: ^3.0.6
  deepgram_speech_to_text: ^2.1.1
  device_calendar: ^4.3.2
  encrypt: ^5.0.3
  enhanced_url_launcher_platform_interface: ^2.1.4
  envied: ^1.0.0
  equatable: ^2.0.7
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.6
  flutter_bloc: ^8.1.6
  flutter_blue_plus: ^1.32.7
  flutter_foreground_task: ^6.5.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.4+3
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  flutter_timezone: ^2.0.0
  go_router: ^14.3.0
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  gradient_borders: ^1.0.1
  groq: ^0.0.5
  growthbook_sdk_flutter: ^3.9.2
  http: ^1.2.1
  instabug_flutter: 14.0.0
  instabug_http_client: 2.5.0
  internet_connection_checker_plus: ^2.5.0
  intl: ^0.19.0
  location: null
  logger: ^2.4.0
  lottie: ^3.1.2
  map_launcher: ^3.3.1
  mixpanel_flutter: ^2.2.0
  objectbox: ^4.0.1
  objectbox_flutter_libs: any
  onesignal_flutter: ^5.2.5
  opus_dart: ^3.0.1
  opus_flutter: ^3.0.2
  package_info_plus: ^8.1.2
  path: ^1.9.0
  path_provider: ^2.1.5
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  provider: ^6.1.2
  record: ^5.1.2
  share_plus: ^10.1.3
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  sign_in_with_apple: ^6.1.1
  swipe: ^0.0.1
  timelines_plus: ^1.0.4
  tuple: ^2.0.2
  upgrader: ^10.3.0
  url_launcher: ^6.3.0
  # url_launcher_platform_interface: null
  uuid: ^4.5.1
  wav: ^1.3.0
  web_socket_channel: ^3.0.1
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      ref: b783000

dependency_overrides:
  http: ^1.2.1
  # opus_flutter_ios:
  #   git:
  #     url: https://github.com/mdmohsin7/opus_flutter.git
  #     path: opus_flutter_ios
  #     ref: dev
  opus_flutter_android:
    git:
      url: https://github.com/mdmohsin7/opus_flutter.git
      path: opus_flutter_android

dev_dependencies:
  build_runner: ^2.4.11
  envied_generator: ^1.0.0
  flutter_flavorizr: ^2.2.3
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  objectbox_generator: ^4.0.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/avm_app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/
    - assets/animations/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
