# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
    match(type: "appstore", git_url: "git@github.com:Craftech360-projects/fastlane.git") # Ensure you have the correct certificates and profiles
    
    build_app(scheme: "Runner") # Build your app
    upload_to_testflight # Upload to TestFlight
  end
end
