# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :custom_lane  do
    match(type: "appstore", readonly: true, git_url: "git@github.com:Craftech360-projects/fastlane.git")
    # Ensure you have the correct certificates and profiles
    
    build_app(scheme: "Runner") # Build your app
    pilot( # Upload your app to TestFlight using Pilot
      username: "apps.cft360@gmail.com", # Replace with your Apple ID
      
      app_identifier: "com.craftech360.avm", # Replace with your app's bundle identifier
      
      changelog: "Add your changelog here" # Provide your changelog
    )
  end
end
